# Generated by Django 3.2 on 2023-10-05 19:14

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='Respuesta correcta')),
                ('texto', models.TextField(blank=True, verbose_name='Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, validators=[core.models.validate_only_letters_and_spaces])),
                ('status', models.CharField(choices=[('E', 'Elaborando examen'), ('R', 'Realizar examen'), ('F', 'Examen Finalizado')], default='E', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(verbose_name='Pregunta:')),
                ('max_puntaje', models.DecimalField(decimal_places=1, default=2, max_digits=6, verbose_name='Maximo Puntaje')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluacione')),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'examenes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='Respuesta Correcta')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Obtenido')),
                ('Notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.nota')),
                ('examenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examenes')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elegirrespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_materia', models.CharField(max_length=200, unique=True, validators=[core.models.validate_only_letters_and_spaces])),
                ('docente', models.ForeignKey(limit_choices_to={'groups__name': 'profesores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='evaluacione',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materia'),
        ),
        migrations.AddField(
            model_name='elegirrespuesta',
            name='examenes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.examenes'),
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Subir Archivo')),
                ('informacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Informacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evaluacione')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
    ]
